= Akagoria world builder manual
Julien Bernard <julien.bernard@univ-fcomte.fr>
v0.5
:toc:
:homepage: https://akagoria.github.io/
:stem: latexmath
:source-highlighter: coderay
:xrefstyle: full

This document provides information for building the world of Akagoria.

WARNING: This is a work in progress, it may change in the future

== Introduction

All the pieces described in <<map>> and in <<data>> are serialized into `akagoria.dat`. The scripts described in <<scripts>> are not serialized and are part of the distributed package.


[[map]]
== Map

The map of Akagoria is built with https://www.mapeditor.org/[Tiled]. It has stem:[2048 \times 2048] tiles of size stem:[32 \times 32].

TIP: It is recommanded to desactivate the minimap as it can slow down Tiled with a big map.

=== Floors

The map is composed of several floors. The floors are numbered with integers, even floors are outside floors, and odd floors are insdide floors. Floor 0 is the floor at the sea level.

.Floors number
[cols="<,^,^"]
|===
|                 | Inside | Outside

| First Basement  | -2 | -1

| Sea level       | 0 | 1
|===

Each floor is composed of a group of layers. The group has an integer property named `floor` and fixed to the floor number. Each layer has a string property named `kind`. Some layers provide graphics while other provide invisible data that is necessary for the game.

[[graphics_layers]]
.Graphics layers on each floor
|===
| Name | Type | Value of `kind`

| Ground | Tile layer | `groundTile`

| Low Tiles | Tile layer | `lowTiles`

| Low Sprites | Object layer | `lowSprites`

| High Tiles | Tile layer | `highTiles`

| High Sprites | Object layer | `highSprites`
|===


Graphics layers are rendered in the order of <<graphics_layers>>. The hero and the NPCs are rendered between "Low Sprites" and "High Tiles".


.Data layers on each floor [[data_layers]]
|===
| Name | Type | Value of `kind`

| Areas | Object layer | `areas`

| Locations | Object layer | `locations`

| Zones | Object layer | `zones`

| Collisions | Object layer | `collisions`
|===


=== Graphics layers

==== Ground tile layer

This layer is used for the ground, so it must cover the whole floor.

This layer must use a single tileset, generally the `Biomes` tileset.

==== Other tile layers

These layers are dedicated to large items that can not be represented with a single sprite.

.Examples of items
[%autowidth.stretch]
|===
| Layer | Items

| Low Tiles | roads, rivers, unreachable areas, ...

| High Tiles | roofs, ...
|===

==== Sprite layers

These layers contains all the small items that are spread all around the world. If the item has an upper part that can cover the hero, then it must go in the "High Sprites" layer. Otherwise, it goes in  the "Low Sprites" layer.

Each sprite in the tileset can have a string property named `shape` that is the collision shape of the sprite. The shapes are assumed to be centered in the tile. If the `shape` property is not present, no collision shape is defined for this tile.

.Shape properties in tilesets
|===
| Value of `shape` | Mandatory properties

| `circle`
a|
- `shape_radius`: the radius of the circle.

| `rectangle`
a|
- `shape_width`: the width of the rectangle
- `shape_height`: the height of the rectangle

|===

=== Data layers

[[areas_layer]]
==== Areas layer

The "Areas" layer contains the name and position of the areas of the world. A location is represented by a _point object_ or an _ellipse object_ with no size.


[[locations_layer]]
==== Locations layer

The "Locations" layer contains special points of interest that can be used in the script (see <<adventure>>). A location is represented by a _point object_ or an _ellipse object_ with no size.


[[zones_layer]]
==== Zones layer

The "Zones" layer contains zones that can trigger an event in the script (see <<adventure>>). Each zone has a string property named `message` that contains the message to be sent. Optionnally, it may have a string property named `requirements` that contains a comma-separated list of requirements. The event is triggered only if the hero has all the given requirements.

A zone is represented by a _rectangle object_ or a _polygon object_.

[[special_messages]]
.Special messages
[%autowidth.stretch]
|====
| Message | Description

| `MoveUp` | Move the hero one floor up (floor number is increased by 2)

| `MoveDown` | Move the hero one floor down (floor number is decreased by 2)
|====


==== Collisions layer

The "Collisions" layer contains the collision shapes that prevent the hero to go in unreachable areas.

A collision shape is represented by the a _polyline object_ or a _polygon object_.


[[data]]
== Data

In this section, all the files are plain https://www.json.org/[JSON] files.

[[characters]]
=== Characters

[source,json]
----
"Alice": {
  "size": { "width": 60, "height": 55 }
}
----


[[dialogs]]
=== Dialogs

[source,json]
----
"Name": {
  "type": "Simple",
  "content": [
    { "speaker": "Alice", "words": "Hello!" },
    { "speaker": "Bob", "words": "Hey you!\nHow are you?" }
  ]
}
----


=== Quests

[[notifications]]
=== Notifications

[source,json]
----
"Welcome": {
  "message": "Welcome to Akagoria!",
  "duration": 3.0
}
----


[[scripts]]
== Scripts

Scripts are written in the http://wren.io/[Wren] language. They are loaded at startup. They contains classes with static functions only.

=== `World` script

This script handles the interactions with the state of the game.

==== Hero functions

`World.moveHero(location)` move the hero to the specified location. The `location` parameter is a valid location name on the map (see <<locations_layer>>).


`World.moveHeroDown()` and `World.moveHeroUp()` are used when the messages `MoveDown` and `MoveUp` respectively are triggered (see <<special_messages>>).


==== Notifications functions

`World.postNotification(notification)` send a notification on the screen. The `notification` parameter is a valid notification name (see <<notifications>>).


==== Requirements functions

`World.addRequirement(requirement)` adds a requirement to the hero.

`World.removeRequirement(requirement)` removes a requirement to the hero.


==== Characters functions

`World.addCharacter(character, location)` add a character in the specified location. The `character` parameter is a valid character name (see <<characters>>). The `location` parameter is a valid location name on the map (see <<locations_layer>>).


==== Dialogs functions

`World.startDialog(dialog)` starts a dialog. The `dialog` parameter is a valid dialog name (see <<dialogs>>).

`World.attachDialogToCharacter(dialog, character)` set the next dialog of a character. The `dialog` parameter is a valid dialog name (see <<dialogs>>). The `character` parameter is a valid character name (see <<characters>>).


[[adventure]]
=== `Adventure` script

This script contains the callbacks that are called by the engine.

`Adventure.initialize()` is called just after script loading. It is responsible for initializing all the other callbacks.

`Adventure.start()` is called at the beginning of the game. It is responsible for setting the initial state of the game.

`Adventure.onMessage(message)` is called when the hero hits a zone. The `message` parameter is the message that is defined in the zone (see <<zones_layer>>).

`Adventure.onDialog(dialog)` is called at the end of a dialog. The `dialog` parameter is the name of the dialog that just ended (see <<dialogs>>).


